### ISSUE TITLE
哥们怎么用啊

### ISSUE THREAD

**Issue by louis16s** [Archill311/One-click-teaching-evaluation-script-of-Guangdong-Ocean-University#1]
能不能细说

**Comment by Archill311** [comment]
油猴插件会用吗？会用的话在评教的页面按一下回车键就可以了。如果不行的话可能是失效了，今年我还没使用过

**Comment by louis16s** [comment]
可以的可以的感谢

Have a nice day
r祺
________________________________
发件人: 程序员跑路 ***@***.***>
发送时间: Monday, June 26, 2023 4:35:59 PM
收件人: Archill311/One-click-teaching-evaluation-script-of-Guangdong-Ocean-University ***@***.***>
抄送: louis16s ***@***.***>; Author ***@***.***>
主题: Re: [Archill311/One-click-teaching-evaluation-script-of-Guangdong-Ocean-University] 哥们怎么用啊 (Issue #1)


油猴插件会用吗？会用的话在评教的页面按一下回车键就可以了。如果不行的话可能是失效了，今年我还没使用过

―

**Comment by Archill311** [comment]
刚刚试了一下，没有问题。
